name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
      # with:
      #   submodules: true

    - name: Setup NuGet.exe
      uses: nuget/setup-nuget@v3
        
    - run: nuget install Microsoft.Windows.WDK.x64 -Version 10.0.26100.6584
    
    - name: Set up MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - run: |
        dir /S
        
    - name: Build 
      run: |
        mkdir build
        cd build
        cmake -G Ninja ..
        cmake --build . --config Debug --target simple
        
    - run: |
        dir /S


