name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
      # with:
      #   submodules: true

    - name: Setup NuGet.exe
      uses: nuget/setup-nuget@v3
        
    - shell: cmd
      run: nuget install Microsoft.Windows.WDK.x64 -Version 10.0.26100.6584
    
    - name: Set up MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - shell: cmd
      working-directory: FindWDK
      run: |
        mkdir build-out
        cd build-out
        cmake ..
        MSBuild.exe FindWDK.sln

    - shell: cmd
      run: |
        dir /S

  # D:\a\wdk-playground\wdk-playground\Microsoft.Windows.WDK.x64.10.0.26100.6584\c\Include\10.0.26100.0\km
    - name: Build
      shell: cmd
      run: |
        set CD_LINUX=%CD:\=/%
        set WDKContentRoot="%CD_LINUX%/Microsoft.Windows.WDK.x64.10.0.26100.6584/c"
        echo %WDKContentRoot%
        mkdir build
        cd build
        cmake -G Ninja .. 
        cmake --build . --config Debug --target simple
        
    - run: |
        dir /S


